stages:
  - build
  - test

build:
  stage: build
  script:
    - sudo echo "hello"


test:
  stage: test
  script:
    # Ensure kubeconfig is available for the cluster
    - echo "Namespace already exists"  # Create namespace if it doesn't exist

