stages:
  - build
  - test


before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

build:
  stage: build
  script:
    - echo "hello"
  only:
    - merge_requests  # Run for merge requests only

test:
  stage: test
  script:
    # Ensure kubeconfig is available for the cluster
    - echo "Namespace already exists"  # Create namespace if it doesn't exist
  only:
    - merge_requests

